version: '3'
services:
  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=influxdb
      - INFLUXDB_ADMIN_USER_TOKEN=influxdb
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=influxdb

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: bitnami/grafana:latest
    ports:
      - "3000:3000"

  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter
    command:
      - "--mysqld.username=application:application"
      - "--mysqld.address=mysql:3306"
    depends_on:
      - mysql

  # 아래는 부하 테스트용 저사양 환경 임의 세팅
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql-privileges.load-test.sql:/docker-entrypoint-initdb.d/mysql-privileges.load-test.sql:ro
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

networks:
  default:
    driver: bridge