version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./src/test/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge